[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
]
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 250
max_test_rejects = 100000

# See more config options https://github.com/gakonst/foundry/tree/master/config